version: '3'
env:
  TEST_DISPLAY: '{{.TEST_DISPLAY | default ":2"}}'
  DEBUG_LEVELS: '{{.LEVELS | default "all"}}'

tasks:
  build:
    cmds:
      - rake

  rebuild:
    cmds:
      - rake clobber; rake

  run:
    cmds:
      - ./subtle -d ${TEST_DISPLAY} -c dev.rb -s /dev/null

  debug:
    cmds:
      - ./subtle -d ${TEST_DISPLAY} -c dev.rb -D -l ${DEBUG_LEVELS} -s /dev/null
